### PR TITLE
Fix Kerrigan bonus levels

### PR DESCRIPTION
**Pull request by Salzkorn**
Since it's been reported as a bug on several occasions, this changes the bonus levels for Supreme/The Infinite Cycle to be a minimum rather than an additive bonus, to be more in line with other granted tech.

Tested by opening Supreme with a level 0 Kerrigan and a level 70 Kerrigan.

### CODE REVIEW

**Comment by MatthewMarinets** [comment]
This is one of the main things keeping me banning no-builds with Kerrigan in them, really hope it makes it in.

**Comment by Ziktofel** [comment]
I think in order to avoid any reports we have to drop this feature at all (and make a logic rule for kerrigan levels, if not possible, return always false and fail to generate if this mission occurs)

**Comment by Ziktofel** [comment]
Due to: https://github.com/Ziktofel/Archipelago/pull/152 it should be for Grant Story Tech only. Also update the variable names for better clarity

**Comment by Ziktofel** [comment]
Redesigned and replaced with something else

**Pull request closed without merging**
